DROP TABLE IF EXISTS T_USER;

CREATE TABLE T_USER (
  USR_ID          VARCHAR(20) NOT NULL COMMENT '사용자ID',
  USR_GRP_ID      VARCHAR(20) NOT NULL COMMENT '사용자 그룹 ID',
  PWD             VARCHAR(64) NOT NULL COMMENT '비밀번호',
  USR_NM          VARCHAR(30) NOT NULL COMMENT '사용자명',
  EMAIL           VARCHAR(20) NOT NULL COMMENT 'EMAIL',
  TEL_NO          VARCHAR(20) COMMENT '전화번호',
  MOBILE_NO       VARCHAR(20) C	MMENT '모바일번호',
  IP_BAND         VARCHAR(20) COMMENT 'IP대역',
  LOGIN_FAIL_CNT  SMALLINT COMMENT '로그인실패횟수',
  PSWD_DUE_DT     CHAR(8) COMMENT '비밀번호만료일',
  PSWD_CHNG_CYCL  INT COMMENT '비밀번호교환주기',
  LST_LOGIN_DT    VARCHAR(17) COMMENT '최종로그인일자',
  LST_LOGIN_TM    VARCHAR(13) COMMENT '최종로그인일시',
  ACNT_LOCK_YN    CHAR(1) COMMENT '계정잠금여부',
  OLD_PWDNO1      VARCHAR(64) COMMENT '이전비밀번호1',
  OLD_PWDNO2      VARCHAR(64) COMMENT '이전비밀번호2',
  STORE_ID	      VARCHAR(12) COMMENT '상점ID',
  CONSTRAINT PK_T_USER PRIMARY KEY(USR_ID,EMAIL)
)COMMENT='사용자정보';

DROP TABLE IF EXISTS T_USER_GROUP;

CREATE TABLE T_USER_GROUP
(
    USR_GRP_ID   VARCHAR(3) NOT NULL COMMENT '사용자그룹ID',
    USR_GRP_NM   VARCHAR(50) NOT NULL COMMENT '사용자그룹명',
    EXPLN        VARCHAR(100) COMMENT '설명',
    PRT_ORD      BIGINT DEFAULT 99999 COMMENT '출력순서',
    CONSTRAINT PK_T_USER_GROUP PRIMARY KEY (USR_GRP_ID)
)COMMENT='사용자그룹정보';

DROP TABLE IF EXISTS T_USER_GROUP_AUTH;

CREATE TABLE T_USER_GROUP_AUTH
(
    USR_GRP_ID  VARCHAR(3) NOT NULL COMMENT '사용자그룹ID',
    MENU_NO     BIGINT NOT NULL COMMENT '메뉴번호',
    AUTH_TP     CHAR(1) NOT NULL COMMENT '권한유형',
    UP_MENU_NO  BIGINT NOT NULL COMMENT '상위메뉴번호',
    MENU_STEP   BIGINT NOT NULL COMMENT '메뉴단계',
    ALGN_ORD    BIGINT NOT NULL COMMENT '정렬순서',
    CONSTRAINT PK_T_USER_GROUP_AUTH PRIMARY KEY (USR_GRP_ID, MENU_NO)
)COMMENT='사용자그룹권한정보';

DROP TABLE IF EXISTS T_LOGIN_HIST;

CREATE TABLE T_LOGIN_HIST
(
    USR_ID       VARCHAR(20) NOT NULL COMMENT '사용자ID',
    LOGIN_DT     CHAR(8) NOT NULL COMMENT '로그인일자',
    SEQ_NO       BIGINT NOT NULL COMMENT '일련번호',
    LOGIN_TM     CHAR(6) NOT NULL COMMENT '로그인시간',
    LOGIN_GW_IP  VARCHAR(20) COMMENT '로그인GW IP',
    LOGOUT_DT    CHAR(8) COMMENT '로그아웃날짜',
    LOGOUT_TM    CHAR(6) COMMENT '로그아웃시간',
    LOGOUT_ST    CHAR(1) COMMENT '로그아웃상태',
    RMRK         VARCHAR(50) COMMENT '비고',
    CONSTRAINT PK_T_LOGIN_HIST PRIMARY KEY (USR_ID, LOGIN_DT, SEQ_NO)
)COMMENT='로그인이력정보';


SELECT *
  FROM T_COMMON_CODE
  ;

DROP TABLE IF EXISTS T_COMMON_CODE;

CREATE TABLE T_COMMON_CODE
(
    GRP_CD 	    VARCHAR(20) NOT NULL COMMENT '공통 코드 목록 아이디',
    DTL_CD          VARCHAR(20) NOT NULL COMMENT '공통 코드',
    DTL_NM          VARCHAR(4000) DEFAULT NULL COMMENT '설명',
    ALGN_ORD        BIT(11) NOT NULL COMMENT '표시 순서',
    USE_YN          VARCHAR(1) DEFAULT 'N' NOT NULL COMMENT '사용 여부',
    CREATE_USER_ID  VARCHAR(20) NOT NULL COMMENT '생성 사용자 아이디',
    CREATE_DATETIME DATE NOT NULL COMMENT '생성 일시',
    UPDATE_USER_ID  VARCHAR(100) NOT NULL COMMENT '변경 사용자 아이디',
    UPDATE_DATETIME DATE NOT NULL COMMENT '변경 일시',
    CONSTRAINT PK_T_COMMON_CODE PRIMARY KEY (GRP_CD, DTL_CD)
)COMMENT='공통코드';

DROP TABLE IF EXISTS T_MENU;

CREATE TABLE T_MENU
(
    MENU_NO       BIGINT NOT NULL COMMENT '메뉴번호',
    MENU_NM       VARCHAR(200) NOT NULL COMMENT '메뉴명',
    UP_MENU_NO    BIGINT COMMENT '상위메뉴번호',
    URL           VARCHAR(256) COMMENT 'URL',
    IMG_PATH      VARCHAR(256) COMMENT '이미지경로',
    HELP_FILE_NM  VARCHAR(256) COMMENT '도움말파일명',
    ORD_NO        BIGINT NOT NULL COMMENT '순서번호',
    PRT_ORD       BIGINT NOT NULL COMMENT '출력순서',
    EXPLN         VARCHAR(100) COMMENT '설명',
    FOLDER_YN     VARCHAR(5) NOT NULL COMMENT '폴더여부',
    CONSTRAINT PK_T_MENU PRIMARY KEY (MENU_NO)
)COMMENT='메뉴정보';
